### ISSUE TITLE
Request: Docker image

### ISSUE THREAD

**Issue by Herjar** [excalith/excalith-start-page#1]
Loving the look of this. Any chance of a docker image?

**Comment by excalith** [comment]
Thanks! I am so glad to see some stars, I wasn't expecting that much attention to be honest ˆˆ 
I never created a docker image before, but was looking for an excuse to try it out! The only problem is this being my bare setup and I update it regularly for my own taste. It still can be a docker image, but would you use it with constant updates? Maybe a "framework"-kinda version can be an image (where I seperate my config to prevent triggering updates) which will be built to let people configure with a more robust config system? What do you think about this? I will think it through and try to find a solution.
Thanks for the idea by the way, sounds lovely!

**Comment by excalith** [comment]
Hello @Herjar, finally had some time to work on the docker image with some goodies such as importing remote configurations through app. Can you please check it out?
```
docker pull excalith/start-page
```
I am pretty new to making docker images, so far it works on my end but would love to hear your experience
