### ISSUE TITLE
[BUG] Opening startpage gives 500 error

### ISSUE THREAD

**Issue by not-alaris** [excalith/excalith-start-page#67]
### Describe The Bug
Upon opening a new tab using the hosted link gives the error:
"500: INTERNAL_SERVER_ERROR 
Code: INTERNAL_DEPLOYMENT_FETCH_FAILED 
ID: iad1::5g8wx-1705527995677-45a89a676c85"
The ID changes each time a new tab is opening. This happens ~80% of the time I open a new tab of the hosted startpage. Sometimes it loads, but not as often as it doesn't. I have changed colors and bookmarks in the configuration code, but that is all.

### To Reproduce

1. Open a new tab of the startpage.

### Expected Behavior
Startpage functions normally, without error.

### Screenshots
<img width="1438" alt="Screenshot 2024-01-17 at 4 52 35 PM" src="https://github.com/excalith/excalith-start-page/assets/72212608/2ac63bca-0ca0-4a86-8161-2bb27fc0df65">

### Specs

- macOS Ventura 13.2.1 (22D68)
- Firefox 121.0.1

**Comment by excalith** [comment]
Hey @not-alaris!

Unfortunately I cannot reproduce this issue on my end, but I am willing to help you as much as I can.
Is this a server deployment? Did you use Docker image? If so, can you show me your compose file?
Also please share console logs as well

Here is what vercel says about this exception:

> The INTERNAL_DEPLOYMENT_FETCH_FAILED error occurs when the system is unable to fetch the deployment. This could happen due to network issues, misconfigurations, or other internal errors that prevent the deployment data from being retrieved.

Please have a look at this documentation and follow some troubleshooting
https://vercel.com/docs/errors/INTERNAL_DEPLOYMENT_FETCH_FAILED

**Comment by not-alaris** [comment]
I am using the demo version, with an extension to set it as my new tab in Firefox on my personal computer. I believe that is was internet connectivity causing the error to occur, and I restarted my computer and reset the config on the demo site, and it has been working. Thanks anyways!

**Comment by excalith** [comment]
Glad to hear the issue is resolved. 
Cheers!
