### ISSUE TITLE
[FEATURE] Dynamically adjust the search engine

### ISSUE THREAD

**Issue by onnttf** [excalith/excalith-start-page#80]
### Please Describe The Feature You Would Like To See
Is it possible to dynamically adjust the search engine? That is, when google is unavailable, use bing instead?

**Comment by excalith** [comment]
Hey @onnttf, you can change, add or remove search engines with different prefixes as you wish.

Please look at the [wiki page](https://github.com/excalith/excalith-start-page/wiki/Configuration#search) for search related options.

If this answers your question, please let me know so I can close this issue.

Cheers!

**Comment by onnttf** [comment]
> Hey @onnttf, you can change, add or remove search engines with different prefixes as you wish.
> 
> Please look at the [wiki page](https://github.com/excalith/excalith-start-page/wiki/Configuration#search) for search related options.
> 
> If this answers your question, please let me know so I can close this issue.
> 
> Cheers!

Hi, I read the document you gave me, but it is actually preconfigured.
Perhaps I didn't express it clearly. I want to automatically select the appropriate search engine based on the situation when the page is opened.
(China blocks Google, so if I don't have a proxy, I'm hoping it can automatically switch to Bing or something.

**Comment by onnttf** [comment]
> Ah, gotcha! Unfortunately, there is no such feature implemented. As a workaround for you, I would suggest using prefixes depending on your connection.
> 
>     * While using proxy, `g search params` will initiate a search through Google
> 
>     * While not using proxy, `d search params` will initiate a search through DuckDuckGo
> 
> 
> You can add the Bing option on your configuration below [these blocks](https://github.com/excalith/excalith-start-page/blob/7f2fdbaf3c481eacb0b4fa4e8e48033f179cf429/data/settings.json#L71)
> 
> EDIT: If there is a service that redirects those queries depending on blocks, you could add that URL to config and launch that service instead. Then, it should reroute to the non-blocked URL.

Got it, thank you for your reply
